#resource "datadog_integration_aws" "integration_01" {
#  account_id = local.account_id
#  role_name  = "DatadogAWSIntegrationPolicy"
#  account_specific_namespace_rules = {
#  api_gateway = false
#  application_elb = false
#  apprunner = false
#  appstream = false
#  appsync = false
#  athena = false
#  auto_scaling = false
#  billing = false
#  budgeting = false
#  certificatemanager = false
#  cloudfront = false
#  cloudhsm = false
#  cloudsearch = false
#  cloudwatch_events = false
#  cloudwatch_logs = false
#  codebuild = false
#  cognito = false
#  collect_custom_metrics = true
#  connect = false
#  crawl_alarms = false
#  directconnect = false
#  dms = false
#  documentdb = false
#  dynamodb = false
#  ebs = false
#  ec2 = false
#  ec2api = false
#  ec2spot = false
#  ecs = false
#  efs = false
#  elasticache = false
#  elasticbeanstalk = false
#  elasticinference = false
#  elastictranscoder = false
#  elb = false
#  emr = false
#  es = false
#  firehose = false
#  fsx = false
#  gamelift = false
#  glue = false
#  inspector = false
#  iot = false
#  kinesis = false
#  kinesis_analytics = false
#  kms = false
#  lambda = false
#  lex = false
#  mediaconnect = false
#  mediaconvert = false
#  mediapackage = false
#  mediatailor = false
#  ml = false
#  mq = false
#  msk = false
#  nat_gateway = false
#  neptune = false
#  network_elb = false
#  networkfirewall = false
#  opsworks = false
#  polly = false
#  rds = false
#  redshift = false
#  rekognition = false
#  route53 = false
#  route53resolver = false
#  s3 = false
#  s3storagelens = false
#  sagemaker = false
#  ses = false
#  shield = false
#  sns = false
#  sqs = false
#  step_functions = false
#  storage_gateway = false
#  swf = false
#  transitgateway = false
#  translate = false
#  trusted_advisor = false
#  usage = false
#  vpn = false
#  waf = false
#  wafv2 = false
#  workspaces = false
#  xray = false
#  }
#}



#https://docs.datadoghq.com/api/latest/aws-integration/#list-namespace-rules
#curl -X GET "https://api.datadoghq.com/api/v1/integration/aws/available_namespace_rules" \
#-H "Content-Type: application/json" \
#-H "DD-API-KEY: 81361cca1bd36b562f809768c63d9f66" \
#-H "DD-APPLICATION-KEY: d9407221f7031d5d543c62f99d74456cf856abe1"
